import { useState } from 'react'
import { StepIndicator } from '@/components/shared/StepIndicator'
import { Button } from '@/components/ui/shadcn/Button'
import { FIFOAllocationTimeline } from '@/components/financial/FIFOAllocationTimeline'

export default function PaymentWizard() {
  const [step, setStep] = useState(0)
  const [amount, setAmount] = useState(20000)
  const steps = ['Student', 'Outstanding', 'Amount', 'Confirm', 'Receipt']
  return <div><StepIndicator steps={steps} current={step} />{step === 0 && <div className="rounded-md border border-border bg-surface p-6"><p className="text-sm text-text-secondary">Lookup student</p><div className="mt-4 flex justify-end"><Button onClick={() => setStep(1)}>Next</Button></div></div>}{step === 1 && <div className="rounded-md border border-border bg-surface p-6"><p className="text-sm text-text-secondary">Outstanding fees table</p><div className="mt-4 flex justify-end gap-2"><Button className="border border-border bg-white text-text-primary" onClick={() => setStep(0)}>Back</Button><Button onClick={() => setStep(2)}>Next</Button></div></div>}{step === 2 && <div className="grid gap-4 rounded-md border border-border bg-surface p-6 md:grid-cols-[60%_40%]"><div><label className="mb-1 block text-[13px] font-medium text-text-primary">Amount</label><input value={amount} onChange={e => setAmount(Number(e.target.value) || 0)} className="h-10 w-full rounded-sm border border-border px-3" /><div className="mt-4 flex justify-end gap-2"><Button className="border border-border bg-white text-text-primary" onClick={() => setStep(1)}>Back</Button><Button onClick={() => setStep(3)}>Next</Button></div></div><FIFOAllocationTimeline items={[{ feeName: 'Tuition', term: 'First', amountApplied: amount - 5000, balance: 0 }, { feeName: 'Development Levy', term: 'First', amountApplied: 5000, balance: 5000 }]} /></div>}{step === 3 && <div className="rounded-md border border-border bg-surface p-6"><p className="text-sm text-text-secondary">Confirm and record payment.</p><div className="mt-4 flex justify-end gap-2"><Button className="border border-border bg-white text-text-primary" onClick={() => setStep(2)}>Back</Button><Button onClick={() => setStep(4)}>Confirm</Button></div></div>}{step === 4 && <div className="rounded-md border border-border bg-surface p-6"><p className="text-sm text-text-secondary">Receipt generated.</p><div className="mt-4 flex justify-end"><Button onClick={() => setStep(0)}>Record another</Button></div></div>}</div>
}
